name: Update LeetCode Stats

on:
  workflow_dispatch:      # Cho phép chạy thủ công nút "Run workflow"
  schedule:
    - cron: "0 0 * * *"   # Tự động chạy mỗi ngày vào 00:00 UTC

jobs:
  update-readme:
    name: Update Readme with LeetCode Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update LeetCode Stats
        uses: Gurupawar/leetcode-stats@v2.1.3
        with:
          leetcode-username: "Souloleveling" 
          update-readme: true
